[project]
name = "breona"
version = "0.1.0"
description = "breona"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "deepagents>=0.6.3",
    "dotenv>=0.9.9",
    "langchain-openai>=1.2.2",
    "requests>=2.34.2",
    "textual>=8.2.7",
    "nonebot-adapter-onebot>=2.4.6",
    "pyjwt>=2.13.0",
    "nonebot2[websockets]>=2.5.0",
    "langchain-core>=1.4.0",
    "rich>=15.0.0",
    "httpx>=0.28.1",
]

[dependency-groups]
dev = [
    "textual-dev>=1.8.0",
]

[tool.nonebot]
plugin_dirs = ["breona/plugins"]
builtin_plugins = []

[tool.nonebot.adapters]
nonebot-adapter-onebot = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" },
]
"@local" = []

[tool.nonebot.plugins]
"@local" = []
